[project]
name = "lula"
version = "0.1.0"
description = "A CLI tool to manage pull requests from the terminal"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "click~=8.2.1",
    "python-gitlab~=6.3.0",
]

[project.scripts]
lula = "lula.cli:main"
